source 'https://rubygems.org'
ruby '2.6.5'

gem 'byebug'
gem 'sinatra'
gem 'sinatra-cross_origin', '~> 0.3.1'
gem 'thin'
gem 'json'
group :development do
  gem 'web-console', '>= 3.3.0'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
